id: PC210F4EE
initial_creation_type: input
source_metadata:
  title: Ngöndro Commentary by Chökyi Drakpa
  language: es
  description: 'The commentary on the preliminary practices of Longchen Nyingtik by
    Chökyi Drakpa (chos kyi grags pa):'
  volume:
    43b66c079be6481dabede487283a6292:
      title: 'A Torch for the Path to Omniscience: A Word by Word Commentary to the
        Longchen Nyingtik Ngöndro'
      parent: null
created_at: '2022-02-28T22:48:13.458581'
last_modified_at: '2022-02-28T22:48:13.458584'
